; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = apps
default_envs = probe

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
monitor_speed = 115200
upload_speed = 460800

[env:probe]
board = m5stack-core-esp32
framework = arduino
lib_deps =
  m5stack/M5Unified@0.2.17
build_src_filter =
  +<probe/src/>

[env:drum-step-sequencer]
board = m5stack-core-esp32
framework = arduino
board_build.partitions = huge_app.csv
build_src_filter =
  +<drum-step-sequencer/src/>
lib_deps =
  m5stack/M5Unified@0.2.17
  fcz2/amy-synth-m5@0.3.1
  musical-clock=file://../musical-clock/packages/musical-clock

[env:native]
platform = native
framework =
lib_deps =
test_framework = unity
test_build_src = no
